#pragma once

#include "ICellularAutomaton.h"
#include "IAnimatedCA.hpp"
#include "IAnimatedCA1D.h"
#include "IAnimatedCA2D.h"
#include "IMooreCA1D.h"
#include "IMooreCA2D.h"
#include "IVonNeumannCA2D.h"
#include "IFirstOrderCA1D.h"
#include "IFirstOrderCA2D.h"
#include "ISecondOrderCA1D.h"
#include "IRandomInitCA.hpp"
#include "ICentralInitCA1D.h"
#include "ICentralInitCA2D.h"
